# Point to robbyrussel oh-my-zsh installation
export ZSH=~/.oh-my-zsh

# Point to .zshrc
export ZSHRC=~/.zshrc

# Visual theme to use for a list of themes, see:
# https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="pygmalion"

# Plugins to load
plugins=(git zsh-autosuggestions)

# Source oh-my-zsh config file
source $ZSH/oh-my-zsh.sh

# Aliases
alias mountpublic='mkdir -p ~/public && sudo mount //fsvs01/public ~/public -o user=skelly1,workgroup=olin.edu,uid=skelly1'
alias tpb='npm run lint && npm test && npm run build:once'
