#!/bin/bash

# Setup global variables to use throughout script
start_path=pwd
script_name=$0
script_path=$(dirname $(readlink -f $script_name))

echo "--- Downloading Zsh ---"
sudo apt-get -y install zsh

echo ""
echo "--- Installing Oh My Zsh ---"
sh -c "$(wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O -)"

echo ""
echo "--- Setting Zsh to default shell ---"
chsh -s $(which zsh)

echo ""
echo "--- Downloading Zsh Auto-Suggestion Plugin ---"
sudo git clone git://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

# Setup zshrc symlink
echo ""
echo "--- Replacing ~/.zshrc with a symbolic link to ~/.dotfiles/zsh/zshrc ---"
ln --verbose --symbolic --no-dereference --force $script_path/zshrc ~/.zshrc


echo ""
echo "--- System reboot may be required for changes to take affect ---"

echo ""
echo "--- Zsh setup is complete ---"
